@BASE_URL=http://localhost:3000

### Generate OTP - Email (Success)
POST {{BASE_URL}}/otp
Content-Type: application/json

{
  "recipientType": "email",
  "recipientValue": "john@doe.com"
}


### Validate OTP (Success)
POST {{BASE_URL}}/otp/validate
Content-Type: application/json

{
  "otp": "123456",
  "recipientType": "email",
  "recipientValue": "john@doe.com"
}