org: abagtech
app: otp-management
service: otp-management-serverless

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-api-gateway-throttling

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 5

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:Query"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/idx_recipient_type_value"

functions:
  generate:
    handler: dist/lambda/generate.generate
    events:
      - httpApi:
          path: /otp
          method: post
          throttling:
            maxRequestsPerSecond: 10
            maxConcurrentRequests: 5
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
      TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID, 'fakevalue'}
      TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN, 'fakevalue'}
      TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER, 'fakevalue'}
      GOOGLE_EMAIL: ${env:GOOGLE_EMAIL, 'fakevalue'}
      GOOGLE_PASSWORD: ${env:GOOGLE_PASSWORD, 'fakevalue'}

  validate:
    handler: dist/lambda/validate.validate
    events:
      - httpApi:
          path: /otp/validate
          method: post
          throttling:
            maxRequestsPerSecond: 10
            maxConcurrentRequests: 5
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

resources:
  Resources:
    OtpTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: recipientType
            AttributeType: S
          - AttributeName: recipientValue
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: idx_recipient_type_value
            KeySchema:
              - AttributeName: recipientType
                KeyType: HASH
              - AttributeName: recipientValue
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

build:
  esbuild: false
  outputBuildFolder: dist/lambda
